const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

async function main() {
  console.log('Generating 300+ records...');
  
  const users = await prisma.user.findMany();
  if (users.length === 0) {
    console.log('Please run the initial seed first to create users: npm run prisma:seed');
    return;
  }
  
  const admin = users.find(u => u.role === 'ADMIN') || users[0];
  const engineer = users.find(u => u.role === 'ENGINEERING') || users[0];

  const stages = await prisma.eCOStage.findMany();
  if (stages.length === 0) {
    console.log('Please run the initial seed first to create ECO stages: npm run prisma:seed');
    return;
  }
  const stageNew = stages.find(s => s.name === 'New') || stages[0];
  const stageReview = stages.find(s => s.name === 'In Review') || stages[0];
  const stageDone = stages.find(s => s.name === 'Done') || stages[0];

  const parts = ['Frame', 'Screen', 'Sensor', 'Module', 'Bracket', 'Engine', 'Motor', 'Panel', 'Cable', 'Housing', 'Controller', 'Battery', 'Lens', 'Connector', 'Switch'];
  const prefixes = ['Pro', 'Max', 'Ultra', 'Nano', 'Lite', 'Plus', 'Eco', 'Quantum', 'Aero', 'Solar', 'Hyper', 'Giga', 'Neo'];

  let productRecords = [];
  console.log('Creating 100 Products and Versions...');
  for (let i = 1; i <= 100; i++) {
    const pName = `${prefixes[i % prefixes.length]} ${parts[i % parts.length]} ${i + 1000}`;
    const basePrice = Math.floor(Math.random() * 500) + 100;
    
    productRecords.push({
      name: pName,
      currentVersion: 1,
      status: 'ACTIVE',
      versions: {
        create: [
          {
            version: 1,
            salePrice: basePrice * 2,
            costPrice: basePrice,
            status: 'ACTIVE'
          }
        ]
      }
    });
  }

  const createdProducts = [];
  for (const prod of productRecords) {
    const inserted = await prisma.product.create({
      data: prod
    });
    createdProducts.push(inserted);
  }

  console.log('Creating 100 BOMs with Components & Operations...');
  const createdBoms = [];
  for (let i = 0; i < 100; i++) {
    const product = createdProducts[i];
    
    // Create random components
    const componentCount = Math.floor(Math.random() * 4) + 2; // 2 to 5 components
    const components = Array.from({ length: componentCount }).map((_, idx) => ({
      componentName: `${parts[Math.floor(Math.random() * parts.length)]} ${idx + 1}X`,
      quantity: Math.floor(Math.random() * 10) + 1,
      unit: 'pcs'
    }));

    const operations = [
      { name: 'Assembly', duration: Math.floor(Math.random() * 60) + 10, workCenter: 'Assembly Station 1' },
      { name: 'Testing', duration: Math.floor(Math.random() * 30) + 5, workCenter: 'Test Station A' }
    ];

    const bom = await prisma.bOM.create({
      data: {
        productId: product.id,
        version: 1,
        status: 'ACTIVE',
        components: { create: components },
        operations: { create: operations }
      },
      include: { components: true }
    });
    createdBoms.push(bom);
  }

  console.log('Creating 150 ECOs...');
  const ecoTypes = ['PRODUCT', 'BOM'];
  
  for (let i = 0; i < 150; i++) {
    const isBom = Math.random() > 0.5;
    const type = isBom ? 'BOM' : 'PRODUCT';
    const product = createdProducts[i % 100];
    const targetBom = isBom ? createdBoms.find(b => b.productId === product.id) : null;
    
    // Distribute statuses
    let status = 'NEW';
    let stageId = stageNew.id;
    const rand = Math.random();
    if (rand > 0.6) {
      status = 'DONE';
      stageId = stageDone.id;
    } else if (rand > 0.3) {
      status = 'IN_REVIEW';
      stageId = stageReview.id;
    }

    const title = `Mass-ECO-${1000 + i}: Enhance ${product.name} ${isBom ? 'BOM Architecture' : 'Pricing'}`;

    const bomComponentChanges = isBom && targetBom ? [
      {
        componentName: 'QC Stamp',
        oldQty: '',
        newQty: '1',
        changeType: 'ADDED'
      }
    ] : null;

    const productChanges = !isBom ? [
      {
        field: 'Sale Price',
        oldValue: '0',
        newValue: '999.99',
        changeType: 'CHANGED'
      }
    ] : null;

    await prisma.eCO.create({
      data: {
        title,
        type,
        productId: product.id,
        bomId: targetBom ? targetBom.id : null,
        userId: engineer.id,
        assignedToId: admin.id,
        status,
        stageId,
        productChanges,
        bomComponentChanges,
        description: 'Auto-generated ECO for system load testing.',
        auditLogs: {
          create: {
            userId: engineer.id,
            action: `ECO auto-generated by mass seeder`,
            actionType: 'CREATE'
          }
        }
      }
    });

    if (i % 25 === 0) {
      console.log(`Generated ${i} ECOs...`);
    }
  }

  console.log('✅ Mass Seed Complete! Successfully generated:');
  console.log(' - 100 Products (with 100 Versions)');
  console.log(' - 100 BOMs (with ~300 Components & 200 Operations)');
  console.log(' - 150 ECOs');
  console.log('Total new records: > 950');
}

main()
  .catch(e => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
